/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post94, git sha1 a1bb0255d) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(b, clk, rst, a);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:8" *)
  output a;
  wire a;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:23" *)
  reg aa = 1'h0;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:23" *)
  reg \aa$next ;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:9" *)
  output b;
  wire b;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:24" *)
  reg bb = 1'h0;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:24" *)
  reg \bb$next ;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\ir.py:508" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:26" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:26" *)
  reg [1:0] \fsm_state$next ;
  (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\ir.py:508" *)
  input rst;
  wire rst;
  always @(posedge clk)
    aa <= \aa$next ;
  always @(posedge clk)
    bb <= \bb$next ;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:26" *)
    casez (fsm_state)
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:27" */
      /* \amaranth.decoding  = "zero/0" */
      2'h0:
          \aa$next  = 1'h0;
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:33" */
      /* \amaranth.decoding  = "one/1" */
      2'h1:
          \aa$next  = 1'h1;
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:39" */
      /* \amaranth.decoding  = "two/2" */
      2'h2:
          \aa$next  = 1'h1;
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:45" */
      /* \amaranth.decoding  = "three/3" */
      2'h3:
          \aa$next  = 1'h0;
    endcase
    (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \aa$next  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:26" *)
    casez (fsm_state)
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:27" */
      /* \amaranth.decoding  = "zero/0" */
      2'h0:
          \bb$next  = 1'h0;
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:33" */
      /* \amaranth.decoding  = "one/1" */
      2'h1:
          \bb$next  = 1'h0;
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:39" */
      /* \amaranth.decoding  = "two/2" */
      2'h2:
          \bb$next  = 1'h1;
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:45" */
      /* \amaranth.decoding  = "three/3" */
      2'h3:
          \bb$next  = 1'h1;
    endcase
    (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \bb$next  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:26" *)
    casez (fsm_state)
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:27" */
      /* \amaranth.decoding  = "zero/0" */
      2'h0:
          \fsm_state$next  = 2'h1;
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:33" */
      /* \amaranth.decoding  = "one/1" */
      2'h1:
          \fsm_state$next  = 2'h2;
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:39" */
      /* \amaranth.decoding  = "two/2" */
      2'h2:
          \fsm_state$next  = 2'h3;
      /* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\encoder.py:45" */
      /* \amaranth.decoding  = "three/3" */
      2'h3:
          \fsm_state$next  = 2'h0;
    endcase
    (* src = "C:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \fsm_state$next  = 2'h0;
    end
  end
  assign b = bb;
  assign a = aa;
endmodule
