/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post94, git sha1 a1bb0255d) */

(* top =  1  *)
(* generator = "Amaranth" *)
module top(direction, clk, rst, step);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:35" *)
  wire \$1 ;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:38" *)
  wire [5:0] \$10 ;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:36" *)
  wire \$3 ;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:37" *)
  wire \$5 ;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:35" *)
  wire \$7 ;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:38" *)
  wire [5:0] \$9 ;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:24" *)
  reg aa = 1'h0;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:24" *)
  reg \aa$next ;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:25" *)
  reg bb = 1'h0;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:25" *)
  reg \bb$next ;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\ir.py:508" *)
  input clk;
  wire clk;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:27" *)
  reg [4:0] counter = 5'h00;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:27" *)
  reg [4:0] \counter$next ;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:9" *)
  output direction;
  wire direction;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\ir.py:508" *)
  input rst;
  wire rst;
  (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:8" *)
  output step;
  wire step;
  assign \$10  = counter + (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:38" *) 1'h1;
  always @(posedge clk)
    bb <= \bb$next ;
  always @(posedge clk)
    aa <= \aa$next ;
  always @(posedge clk)
    counter <= \counter$next ;
  assign \$1  = counter < (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:35" *) 4'he;
  assign \$3  = counter > (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:36" *) 2'h2;
  assign \$5  = ~ (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:37" *) aa;
  assign \$7  = counter < (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:35" *) 4'he;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \bb$next  = 1'h1;
    (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \bb$next  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \aa$next  = aa;
    (* full_case = 32'd1 *)
    (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:35" *)
    if (\$1 ) begin
      (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:36" *)
      if (\$3 ) begin
        \aa$next  = \$5 ;
      end
    end else begin
      \aa$next  = 1'h0;
    end
    (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \aa$next  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \counter$next  = counter;
    (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\steps.py:35" *)
    if (\$7 ) begin
      \counter$next  = \$10 [4:0];
    end
    (* src = "c:\\Users\\mohan\\Developer\\verilog\\qaudrature\\.venv\\Lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \counter$next  = 5'h00;
    end
  end
  assign \$9  = \$10 ;
  assign direction = bb;
  assign step = aa;
endmodule
